#!/bin/bash

#Path where you want to save scans
path=/home/$USER/Pictures/Scans

for i in $(seq -w 999 );
do
FILE=scan_$i.pmn
scanresult=scan_$i.jpg

if [ ! -e $path/$scanresult ]; then
echo "Scanning... Please wait"
#Change printer information below
scanimage -d 'smfp:SAMSUNG SCX-3400 Series on 192.168.0.20' --resolution 300 > $path/$FILE
convert $path/$FILE $path/$scanresult
#Removes the pmn file
rm $path/$FILE
exit 0
fi

done
