#!/bin/bash

#Extend the array if you want to have more scans with this script in the same folder
ARRAY=(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27)

#Path where you want to save scans
path=/home/$USER/Pictures


for i in "${ARRAY[@]}"
do
FILE=scan_0$i.pmn
scanresult=scan_0$i.jpg

if [ ! -e $path/$scanresult ]; then
echo "Scanning... Please wait"
#Change printer information below
scanimage -d 'smfp:SAMSUNG SCX-3400 Series on 192.168.0.20' --resolution 300 > $path/$FILE
convert $path/$FILE $path/$scanresult
#Removes the pmn file
rm $path/$FILE
exit 0
fi

done
